INSERT INTO `gcp-gfb-sai-tracking-gold.applaydu.kpi_ident_campaign` (
    game_id,
    ident_id,
    store,
    source,
    methods,
    fdate,
    fcountry,
    fcampaigncountry,
    in_cms,
    clicks,
    impressions_minisite,
    impressions_visitid_minisite,
    impressions_anonid_minisite,
    minisite_engagements,
    legalaccepted_minisite,
    legaldenied_minisite,
    autoredirect_minisite,
    openstores_minisite,
    visit_web_ar_page_minisite,
    save_screen_shot_minisite,
    installreferral,
    installreferral_inapp_and_scan,
    matchingsafebox,
    matchedipsafebox,
    store_referral_aws,
    downloads,
    internal_scans,
    load_time
)
(
SELECT 
    game_id,
    ident_id,
    store,
    source,
    methods,
    TIMESTAMP(fdate),
    fcountry,
    fcampaigncountry,
    in_cms,
   clicks,
impressions_minisite,
impressions_visitid_minisite,
impressions_anonid_minisite,
minisite_engagements,
legalaccepted_minisite,
legaldenied_minisite,
autoredirect_minisite,
openstores_minisite,
visit_web_ar_page_minisite,
save_screen_shot_minisite,
installreferral,
installreferral_inapp_and_scan,
matchingsafebox,
matchedipsafebox,
store_referral_aws,
    CASE WHEN game_id IN (81335, 82471) THEN GREATEST(installreferral, matchedipsafebox, matchingsafebox) ELSE GREATEST(installreferral, matchedipsafebox) END as downloads,
    internal_scans,
    CURRENT_TIMESTAMP() as load_time
FROM (
    SELECT 
        game_id,
        tblresult.ident_id as ident_id,
        REPLACE(REPLACE(REPLACE(REPLACE(CAST(game_id AS STRING), '81335', 'App Store'), '81337', 'Google Play'), '82487', 'Desktop'), '82471', 'AppInChina') as store,
        utm_source as source,
        utm_medium as methods,
        DATE(fdate) as fdate,
        fcountry as fcountry,
        CASE WHEN `gcp-gfb-sai-tracking-gold.applaydu.ident_info`.country <> '' THEN `gcp-gfb-sai-tracking-gold.applaydu.ident_info`.country ELSE fcountry END as fcampaigncountry,
        CASE WHEN tblresult.ident_id IN (SELECT DISTINCT ident_id FROM `gcp-gfb-sai-tracking-gold.applaydu.ident_info`) THEN 'In Cms' ELSE 'Not in CMS' END as in_cms,
        SUM(CASE WHEN kpi = 'QR Impressions' THEN event_count ELSE 0 END) as clicks,
        SUM(CASE WHEN kpi = 'Minisite Impressions' THEN event_count ELSE 0 END) as impressions_minisite,
        SUM(CASE WHEN kpi = 'Minisite Unique Visiters' THEN event_count ELSE 0 END) as impressions_visitid_minisite,
        SUM(CASE WHEN kpi = 'Minisite Unique Users' THEN event_count ELSE 0 END) as impressions_anonid_minisite,
        SUM(CASE WHEN kpi = 'Minisite Engagements' THEN event_count ELSE 0 END) as minisite_engagements,
        SUM(CASE WHEN kpi = 'LEGAL ACCEPTED' THEN event_count ELSE 0 END) as legalaccepted_minisite,
        SUM(CASE WHEN kpi = 'LEGAL DENIED' THEN event_count ELSE 0 END) as legaldenied_minisite,
        SUM(CASE WHEN kpi = 'AUTO REDIRECT' THEN event_count ELSE 0 END) as autoredirect_minisite,
        SUM(CASE WHEN kpi = 'Open Stores' THEN event_count ELSE 0 END) as openstores_minisite,
        SUM(CASE WHEN kpi = 'VISIT WEB AR PAGE' THEN event_count ELSE 0 END) as visit_web_ar_page_minisite,
        SUM(CASE WHEN kpi = 'SAVE SCREEN SHOT' THEN event_count ELSE 0 END) as save_screen_shot_minisite,
        SUM(CASE WHEN kpi = 'InstallReferral' THEN event_count ELSE 0 END) as installreferral_store,
        SUM(CASE WHEN kpi = 'InstallReferral in App' THEN event_count ELSE 0 END) as installreferral_inapp,
        SUM(CASE WHEN kpi = 'InstallReferral in App and Scan' THEN event_count ELSE 0 END) as installreferral_inapp_and_scan,
        CASE WHEN game_id IN (81335) THEN (SUM(CASE WHEN kpi = 'InstallReferral' THEN event_count ELSE 0 END)) ELSE GREATEST((SUM(CASE WHEN kpi = 'InstallReferral' THEN event_count ELSE 0 END)), (SUM(CASE WHEN kpi = 'InstallReferral in App' THEN event_count ELSE 0 END))) END as installreferral,
        SUM(CASE WHEN kpi = 'Matching safebox' THEN event_count ELSE 0 END) as matchingsafebox,
        SUM(CASE WHEN kpi = 'Matched IP Safebox' THEN event_count ELSE 0 END) as matchedipsafebox,
        SUM(CASE WHEN kpi = 'store_referral_aws' THEN event_count ELSE 0 END) as store_referral_aws,
        SUM(CASE WHEN kpi = 'Internal Scans' THEN event_count ELSE 0 END) as internal_scans
    FROM `gcp-gfb-sai-tracking-gold.applaydu.ident_campaign` tblresult
    LEFT JOIN `gcp-gfb-sai-tracking-gold.applaydu.ident_info` 
    ON `gcp-gfb-sai-tracking-gold.applaydu.ident_info`.ident_id = tblresult.ident_id
    WHERE DATE(fdate) >= '2025-02-01'
    GROUP BY game_id, utm_medium, fcountry, tblresult.ident_id, utm_source, fdate, fcampaigncountry
)
)